// Same-origin data fetcher.
//
// HISTORY: this file used to call https://api.github.com/repos/.../contents/articles
// to list the article JSON files. That endpoint is rate-limited to 60 requests
// per hour per IP for unauthenticated callers. Once the limit was exhausted,
// every subsequent visitor's browser fell into the mock-data fallback and the
// site looked broken ("Article not found"). This rewrite eliminates the
// GitHub API entirely. All data is served from the same origin (compareelite.com)
// via Vercel's static-file CDN — no rate limit, no third-party dependency.
//
// The manifest at /data/articles-manifest.json is the authoritative slug list
// (regenerated by .github/workflows/update-manifest.yml on every push). Each
// individual article JSON lives at /articles/<slug>.json and is also served
// statically.

const CACHE_DURATION = 5 * 60 * 1000;          // 5 minutes (article-list cache)
const MANIFEST_CACHE_DURATION = 2 * 60 * 1000; // 2 minutes (manifest TTL — short so additions/deletions are picked up quickly)

class GitHubAPI {
    constructor() {
        // Empty string = same-origin relative URL. Works in production
        // (compareelite.com) and in any local preview that serves the repo
        // root statically. No CORS, no auth, no rate limit.
        this.baseUrl = '';
    }

    _isCacheValid(cacheKey, duration) {
        const ttl = duration !== undefined ? duration : CACHE_DURATION;
        const cached = localStorage.getItem(cacheKey);
        if (!cached) return false;

        try {
            const parsed = JSON.parse(cached);
            const now = new Date().getTime();
            return (now - parsed.timestamp) < ttl;
        } catch (e) {
            return false;
        }
    }

    _getCachedData(cacheKey) {
        try {
            const cached = localStorage.getItem(cacheKey);
            return JSON.parse(cached).data;
        } catch (e) {
            return null;
        }
    }

    _setCachedData(cacheKey, data) {
        const cacheObj = {
            timestamp: new Date().getTime(),
            data: data
        };
        localStorage.setItem(cacheKey, JSON.stringify(cacheObj));
    }

    // Fetch the lightweight manifest. Used as the canonical slug list and as
    // the cache-invalidation signal — when its `slugs` array diverges from
    // the cached article list, the cache is busted and we re-fetch.
    async _getManifest() {
        const cacheKey = 'ce_cache_manifest';

        if (this._isCacheValid(cacheKey, MANIFEST_CACHE_DURATION)) {
            return this._getCachedData(cacheKey);
        }

        try {
            const response = await fetch(
                `${this.baseUrl}/data/articles-manifest.json`,
                { cache: 'no-store' }
            );
            if (!response.ok) return null;
            const manifest = await response.json();
            this._setCachedData(cacheKey, manifest);
            return manifest;
        } catch (e) {
            return null;
        }
    }

    async getArticlesList() {
        const cacheKey = 'ce_cache_articles_list';

        const manifest = await this._getManifest();

        // Cache hit path — return cached articles only when they exactly match
        // the manifest's current slug set (so a deletion or addition busts it).
        if (manifest && this._isCacheValid(cacheKey)) {
            const cached = this._getCachedData(cacheKey);
            if (cached) {
                const cachedSlugs = new Set(cached.map(a => a.slug));
                const manifestSlugs = new Set(manifest.slugs);
                const inSync =
                    manifest.slugs.every(s => cachedSlugs.has(s)) &&
                    cached.every(a => manifestSlugs.has(a.slug));
                if (inSync) return cached;
                localStorage.removeItem(cacheKey);
            }
        } else if (this._isCacheValid(cacheKey)) {
            return this._getCachedData(cacheKey);
        }

        // Cache miss path — fetch each article JSON in parallel from same origin.
        // No GitHub API call, no rate limit, no third-party dependency.
        if (!manifest || !Array.isArray(manifest.slugs) || manifest.slugs.length === 0) {
            // Manifest unavailable — return whatever we last cached, or empty.
            return this._getCachedData(cacheKey) || [];
        }

        try {
            const articlesPromises = manifest.slugs.map(slug =>
                fetch(`${this.baseUrl}/articles/${slug}.json`)
                    .then(res => res.ok ? res.json() : null)
                    .catch(() => null)
            );

            const articles = (await Promise.all(articlesPromises)).filter(a => a !== null);

            // Sort by date, newest first.
            articles.sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0));

            this._setCachedData(cacheKey, articles);
            return articles;
        } catch (error) {
            console.error('Failed to fetch articles:', error);
            // Last resort: whatever's cached, even if stale.
            return this._getCachedData(cacheKey) || [];
        }
    }

    async getArticle(slug) {
        // Direct fetch is faster than walking the full list when we only need one.
        // Falls back to the list-and-find path if the direct fetch fails.
        try {
            const response = await fetch(`${this.baseUrl}/articles/${slug}.json`, { cache: 'no-store' });
            if (response.ok) return await response.json();
        } catch (e) {
            // fall through
        }
        const articles = await this.getArticlesList();
        return articles.find(a => a.slug === slug) || null;
    }

    async getProducts() {
        const cacheKey = 'ce_cache_products';
        if (this._isCacheValid(cacheKey)) return this._getCachedData(cacheKey);

        try {
            const response = await fetch(`${this.baseUrl}/products.json`);
            if (!response.ok) throw new Error('Not found');
            const data = await response.json();
            this._setCachedData(cacheKey, data);
            return data;
        } catch (error) {
            return [];
        }
    }

    async getAnalytics() {
        const cacheKey = 'ce_cache_analytics';
        if (this._isCacheValid(cacheKey)) return this._getCachedData(cacheKey);

        try {
            const response = await fetch(`${this.baseUrl}/data/analytics.json`);
            if (!response.ok) throw new Error('Not found');
            const data = await response.json();
            this._setCachedData(cacheKey, data);
            return data;
        } catch (error) {
            return this._getMockAnalytics();
        }
    }

    _getMockAnalytics() {
        return {
            revenue: '$0',
            traffic: '0',
            clicks: '0',
            conversions: '0%',
            topArticles: []
        };
    }
}

const githubAPI = new GitHubAPI();
